### ISSUE TITLE
Improve Readability on Mobile Screens

### ISSUE THREAD

**Issue by samuelgrigolato** [opensanca/transparencia#1]
Currently the font is rather small on mobile screens. This could be better handled.

**Comment by daviguelfi** [comment]
I can do that, but I have a question. When does this resolution get hard to read?

**Comment by samuelgrigolato** [comment]
I don't know exactly, but when I open the website on my smartphone it becomes clear that the page is not designed for small screens.

**Comment by daviguelfi** [comment]
I made some tests and start get hard when width is equal a 250px, I'll try to more times and if I have some questions, I sent here

**Comment by samuelgrigolato** [comment]
Done, was missing a meta tag (viewport) :]
